# El Plantío 360 - SonarQube.
# Autor: Marcos Zamorano Lasso
# Práctica 3 - Sistemas Distribuidos
sonar.projectKey=plantio360
sonar.projectName=El Plantío 360
sonar.projectVersion=1.0.0
sonar.sources=src/main/java,src/main/resources,python-api
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
